version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:18.04
   environment:
      GIT_EMAIL: kitkatmukherjee2015@gmail.com
      GIT_NAME: bikram557
      VERSION: 2.2
   steps:
      - run:
          command: |
           echo HELLO.!
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
