name: Bot Deploy

on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{secrets.GH_TOKEN}}
  CONFIG: ${{secrets.CONFIG}}

jobs:
  procces:
    runs-on: ubuntu-latest
    container:
      image: anggit86/userbot:beta
    steps:
      - name: clone source
        run: |
          git clone https://github.com/NFS86/GeezProjects nfsbot
          cd nfsbot
          curl $CONFIG -o config.env
      - name: Run Bot..
        run: |
          cd nfsbot
          bash start &
          sleep 300m
