name: Bot Deploy

on:
  workflow_dispatch:

jobs:
  procces:
    runs-on: ubuntu-latest
    steps:
      - name: build bot
        run: |
          git clone https://NFS86:$GH_TOKEN@github.com/NFS86/Man-Userbot ~/home/nfsbot
          cd ~/home/nfsbot
          curl $CONFIG -o config.env
          sudo docker build . -t nfsbot
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
          CONFIG: ${{secrets.CONFIG}}
      - name: Run Bot..
        run: |
          cd ~/home/nfsbot
          sudo docker run nfsbot &
          sleep 300m
