name: Bot Deploy 1

on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{secrets.GH_TOKEN}}
  CONFIG: ${{secrets.CONFIG}}

jobs:
  procces:
    runs-on: ubuntu-latest
    container:
      image: anggit86/userbot:beta
    steps:
      - name: clone source
        run: |
          git config --global user.email jarbull86@gmail.com
          git config --global user.name NFS86
          git clone https://NFS86:$GH_TOKEN@github.com/NFS86/GeezProjects nfsbot
          cd nfsbot
          curl $CONFIG -o config.env
      - name: Run Bot..
        run: |
          cd nfsbot
          bash start &
          sleep 300m
          git add . -f
          git commit -m "Bot Sesions Update | 1"
