name: Bot Deploy

on:
  workflow_dispatch:
  push:

env:
  GH_TOKEN: ${{secrets.GH_TOKEN}}

jobs:
  procces:
    runs-on: ubuntu-latest
    steps:
      - name: build bot
        run: |
          git clone https://NFS86:$GH_TOKEN@github.com/NFS-projects/NFS-UserBot ~/home/nfsbot
          cd ~/home/nfsbot
          sudo docker build . -t nfsbot
      - name: Run Bot..
        run: |
          cd ~/home/nfsbot
          sudo docker run nfsbot &
          sleep 10m
          git config --global --replace-all user.email jarbull86@gmail.com
          git config --global --replace-all user.name NFS86
          git add . -f
          git commit -asm "NFS-UserBot: session update"
          git push
