name: Bot Deploy

on:
  push:
  workflow_dispatch:

jobs:
  deploy-database:
    name: DataBase
    runs-on: ubuntu-latest
    container: node:latest

    services:
      postgres:
        image: postgres:latest`
        env:
          POSTGRES_DB: nfs-userbot
          POSTGRES_PASSWORD: bebas
          POSTGRES_PORT: 5432
          POSTGRES_USER: nfs86
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      bot:
        image: anggit86/nfsuserbot:latest`
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
          CONFIG_FILE_URL: ${{secrets.CONFIG}}

    steps:
      - name: Install PostgreSQL client
        run: |
          apt-get update
          apt-get install --yes postgresql-client

      - name: Query database
        run: |
          psql -h postgres -d postgres_db -U postgres_user -c 'SELECT 5;'
        env:
          PGPASSWORD: bebas
