name: Bot Deploy

on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{secrets.GH_TOKEN}}
  CONFIG: ${{secrets.CONFIG}}

jobs:
  procces:
    runs-on: ubuntu-latest
    container:
      image: anggit86/manuserbot:beta
    steps:
      - name: clone source
        run: |
          git clone https://NFS86:$GH_TOKEN@github.com/NFS86/Man-Userbot nfsbot
          cd nfsbot
          curl $CONFIG -o config.env
      - name: Run Bot..
        run: |
          cd nfsbot
          bash start &
          sleep 300m
