name: Bot Deploy

on:
  push:
  workflow_dispatch:

env:
  GH_TOKEN: ${{secrets.GH_TOKEN}}
  CONFIG_FILE_URL: ${{secrets.CONFIG}}

jobs:
  procces:
    runs-on: ubuntu-latest
    container:
      image: anggit86/manuserbot:beta
    steps:
      - name: clone source
        run: |
          git config --global user.email jarbull86@gmail.com
          git config --global user.name NFS86
          git clone https://NFS86:$GH_TOKEN@github.com/NFS86/NFS-Userbot -b dev nfsbot
          cd nfsbot
          curl $CONFIG_FILE_URL -o config.env
      - name: Run Bot..
        run: |
          cd nfsbot
          bash start &
          sleep 5m
          rm -rf config.env
          git add . -f
          git commit -asm "Bot Sesions Update | $(/bin/date)"
          git push
      - name: Commit Auto Run.
        run: |
          git clone https://NFS86:$GH_TOKEN@github.com/NFS-projects/bot-deploy
          cd bot-deploy
          git commit --allow-empty -m "Bot Deploy | $(/bin/date)"
          git push
