name: Bot Deploy

on:
  push:
  workflow_dispatch:

env:
  GH_TOKEN: ${{secrets.GH_TOKEN}}
  CONFIG_FILE_URL: ${{secrets.CONFIG}}
      
jobs:
  deploy-bot:
    name: NFS-UserBot
    runs-on: ubuntu-latest
    container: anggit86/nfsuserbot:latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: nfs-userbot
          POSTGRES_PASSWORD: bebas
          POSTGRES_PORT: 5432
          POSTGRES_USER: nfs86
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Install PostgreSQL client
        run: |
          apt-get update
          apt-get install --yes postgresql-client

      - name: Query database
        run: |
          psql -h postgres -d nfs-userbot -U nfs86 -c 'SELECT 100;'
        env:
          PGPASSWORD: bebas

      - name: clone source
        run: |
          git config --global user.email jarbull86@gmail.com
          git config --global user.name NFS86
          git clone https://NFS86:$GH_TOKEN@github.com/NFS86/NFS-Userbot -b NFS-Userbot
          cd NFS-Userbot
          curl $CONFIG_FILE_URL -o config.env

      - name: Run Bot..
        run: |
          cd NFS-Userbot
          bash start &
          sleep 300m

      - name: Commit Auto Run.
        run: |
          git clone https://NFS86:$GH_TOKEN@github.com/NFS-projects/bot-deploy
          cd bot-deploy &
          git commit --allow-empty -m "Bot Deploy | $(/bin/date)"
          git push
